baseURL = 'https://adalbertofjr.github.io/pinkfloyd-mother.github.io/'
languageCode = 'en-us'
title = 'Pink Floyd - Mother'
theme = 'ananke'

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"